(()=>{
 const ja=new URLSearchParams(location.search).get('lang')==='ja';document.querySelector(`[data-lang="${ja?'ja':'ko'}"]`)?.classList.add('active');if(!ja)return;
 window.jp=true;document.documentElement.lang='ja';document.title='玄問 — 易経の智慧をたずねる';const $j=s=>document.querySelector(s),set=(s,t)=>{const e=$j(s);if(e)e.textContent=t};
 set('.brand span','玄問');set('#openGuide','易経占いの見方');set('#intro .eyebrow','玄問 - 易経の智慧をたずねる');$j('#intro h1').innerHTML='今、心に浮かぶ<br><em>ひとつの問い</em>は何ですか？';$j('#intro .lead').innerHTML='答えを決めつけず、状況の流れを見つめてください。<br>問いを明確にし、心を静めて六回コインを投げます。';set('.question-box span','あなたの問い');$j('#question').placeholder='例：今始めようとしていることを、どう捉えればよいでしょうか？';$j('#begin').innerHTML='心を整えて始める <span>→</span>';set('.privacy','問いは保存・送信されません。');set('#stepText','初爻');set('.progress small','下から上へ卦を組み立てます');set('#castNote','問いを心の中で読み、コインを投げてください。');$j('#toss').innerHTML='コインを投げる <span>✦</span>';set('#result>.eyebrow','現在の流れ · 本卦（ほんか）');set('.reading .advice b','今日の助言');set('.change-heading>span','変化の方向');set('#changeTitle','本卦から之卦へ');set('.change-heading p','之卦は本卦の別名ではなく、変爻が動いた後に向かう流れです。');const fs=document.querySelectorAll('.flow-card small'),fsp=document.querySelectorAll('.flow-card>span');fs[0].textContent='現在の流れ · 本卦';fsp[0].textContent='今置かれている状況と姿勢';fs[1].textContent='変化後の流れ · 之卦';
 const st=document.querySelectorAll('.section-title');[['卦の構造','上卦と下卦が示す流れ'],['分野別の読み','問いを現実に照らす'],['変爻の読み','変化が始まる位置']].forEach((x,i)=>{st[i].querySelector('p').textContent=x[0];st[i].querySelector('h3').textContent=x[1]});document.querySelectorAll('.trigram-grid small')[0].textContent='上卦 · 外側の流れ';document.querySelectorAll('.trigram-grid small')[1].textContent='下卦 · 内面の基盤';['仕事と目標','人間関係と対話','お金と暮らし','心と成長'].forEach((t,i)=>document.querySelectorAll('.topic-grid span')[i].textContent=t);set('.reflection>p','今日の内省の問い');set('.reflection small','答えを急がず、浮かんだことを一文で書いてみましょう。');set('#again','新しい問いでもう一度見る');set('.disclaimer','易経の解釈は自分を見つめるための思索の道具です。重要な判断は専門家の助言と現実的な情報も併せてご検討ください。');set('footer p','変化の理を通して自分を映す時間');
 const g=document.querySelectorAll('#guide li');set('#guide h2','よい問いが深い気づきを開きます');g[0].innerHTML='<b>ひとつのテーマに集中します。</b><span>「できますか？」より「何に気づくべきですか？」という開かれた問いがおすすめです。</span>';g[1].innerHTML='<b>コインを六回投げます。</b><span>爻は大地から天へ、下から上に積み上げます。</span>';g[2].innerHTML='<b>卦を鏡として読みます。</b><span>予言ではなく、今の流れと姿勢を見つめる手がかりにしてください。</span>';
 const names=['乾為天','坤為地','水雷屯','山水蒙','水天需','天水訟','地水師','水地比','風天小畜','天沢履','地天泰','天地否','天火同人','火天大有','地山謙','雷地豫','沢雷随','山風蠱','地沢臨','風地観','火雷噬嗑','山火賁','山地剥','地雷復','天雷无妄','山天大畜','山雷頤','沢風大過','坎為水','離為火','沢山咸','雷風恒','天山遯','雷天大壮','火地晋','地火明夷','風火家人','火沢睽','水山蹇','雷水解','山沢損','風雷益','沢天夬','天風姤','沢地萃','地風升','沢水困','水風井','沢火革','火風鼎','震為雷','艮為山','風山漸','雷沢帰妹','雷火豊','火山旅','巽為風','兌為沢','風水渙','水沢節','風沢中孚','雷山小過','水火既済','火水未済'];
 const themes=['創造の力','受けとめ育む力','始まりの混乱を越える','学びによって明るくなる','時を信じて待つ','争いより本質を見る','秩序ある力','助け合い近づく','小さく蓄える','礼を守って進む','滞りが解ける','閉塞の中で中心を守る','志で人を結ぶ','豊かさを正しく治める','謙虚さの力','喜びと準備','流れに従う','古い問題を正す','近づき育てる','一歩引いて観る','障害を明確に除く','美と本質の調和','削ぎ落として守る','本来の道へ戻る','無心と誠実','大きな力を蓄える','自分を養うもの','重荷を賢く越える','困難の中で道を学ぶ','明るく見分ける','心が響き合う','持続する力','退く智慧','強い力を正しく使う','明るい方へ進む','暗闇で光を守る','身近な関係の秩序','違いの中で道を探す','迂回する智慧','緊張が解ける','減らして本質を得る','分かち合って増す','決断の時','思いがけない出会い','人と志が集まる','一歩ずつ上昇する','困窮の中で志を守る','尽きない源を整える','時にかなった変革','新しい器を作る','驚きの後に目覚める','止まって静まる','順を追って育つ','立場と時を見る','豊かさの頂点','旅人の礼','柔らかく浸透する','喜びで語り合う','隔たりを解く','節度を設ける','真心が通じる','小事を丁寧に','成し遂げた後を守る','完成前の最後の一歩'];Object.values(hexagrams).forEach(h=>{h[1]=names[h[0]-1];h[3]=themes[h[0]-1];h[4]=`この卦は「${h[3]}」を中心に、今の状況と自分の姿勢を見つめるよう促しています。結論を急がず、変化の順序を丁寧に確かめてください。`;h[5]='今日できる小さく誠実な行動を一つ選び、無理なく実行しましょう。'});
 detailedReading=function(h,key){const tri={'111':['乾・天','創造と健やかな前進'],'000':['坤・地','受容と育成'],'100':['震・雷','始まりと行動'],'010':['坎・水','困難と深い学び'],'001':['艮・山','停止と境界'],'011':['巽・風','柔らかな浸透'],'101':['離・火','明晰さと結びつき'],'110':['兌・沢','喜びと対話']},lo=tri[key.slice(0,3)],up=tri[key.slice(3,6)];set('#lowerTri',lo[0]);set('#lowerMeaning',lo[1]+'の力が内面の土台にあります。');set('#upperTri',up[0]);set('#upperMeaning',up[1]+'の力が外側の状況に現れます。');set('#structureReading',`内なる${lo[0]}と外なる${up[0]}の関係を読み、「${h[3]}」を今の問いに照らしてください。ひとつの意味に決めつけず、両者の動きを観察しましょう。`);set('#workReading','目的を明確にし、今できる一歩を選びます。原則を守りながら方法は柔軟に整えましょう。');set('#relationReading','相手を変えようとせず、事実と感情を分けて聴きます。短く誠実な対話を心がけましょう。');set('#moneyReading','目先の利益だけでなく、出入りのバランスと持続可能性を確認しましょう。');set('#mindReading',`「${h[3]}」の姿勢を心に置き、結果よりも今の自分が選べる行動に集中しましょう。`);const movers=current.map((x,i)=>x.change?i:-1).filter(i=>i>=0),box=$j('#movingList'),labels=['初爻','二爻','三爻','四爻','五爻','上爻'];box.innerHTML='';if(movers.length){$j('#movingSection').classList.remove('hidden');movers.forEach(i=>{const d=document.createElement('div');d.className='moving-item';d.innerHTML=`<b>${labels[i]}の変化</b><p>この位置から変化が始まります。今の段階と役割を確認し、極端に走らず次の流れを整えてください。</p>`;box.appendChild(d)})}else $j('#movingSection').classList.add('hidden');set('#reflectionQuestion',`「${h[3]}」という視点から、今日変えられる最も小さな行動は何でしょうか？`)};
 const toss=$j('#toss');toss.addEventListener('click',()=>setTimeout(()=>{const n=current.length;if(!$j('#casting').classList.contains('hidden')){set('#stepText',n<6?`${['二','三','四','五','上'][n-1]}爻`:'六爻が完成');set('#castNote',n<6?`${n}本目の爻が置かれました。呼吸を整えて次へ進みましょう。`:'卦が完成しました。');if(n===6)toss.textContent='解釈を見る →'}else{const h=hexagrams[current.map(x=>x.yang?1:0).join('')];set('#hexNo',`第${h[0]}卦`);const movers=current.map((x,i)=>x.change?['初爻','二爻','三爻','四爻','五爻','上爻'][i]:null).filter(Boolean);set('#changeSummary',`${movers.join('・')}が変化`);const changed=current.map(x=>x.change?!x.yang:x.yang).map(x=>x?1:0).join(''),ch=hexagrams[changed];if(ch){set('#changedName',`第${ch[0]}卦 ${ch[1]} · ${ch[2]}`);set('#changedText',`「${ch[3]}」の流れへ向かいます。`)}set('#flowCurrentName',`第${h[0]}卦 ${h[1]} · ${h[2]}`)}},850));
})();
